name: personalia
description: "Aplikasi SDM Farmagitechs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.2.1
  sliding_up_panel: ^2.0.0+1
  encrypt: ^5.0.3
  intl: ^0.19.0
  location: ^6.0.2
  geocoding: ^3.0.0
  popover: ^0.3.0+1
  dropdown_button2: ^2.3.9
  calendar_date_picker2: ^1.1.5
  flutter_widget_from_html: ^0.15.1
  quickalert: ^1.1.0
  restart_app: ^1.2.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  path: ^1.9.0
  sentry_flutter: ^8.3.0
  hl_image_picker: ^1.2.16
  image: ^4.2.0
  hl_image_picker_ios: ^1.2.10
  photo_view: ^0.15.0
  google_mlkit_face_detection: 0.11.0
  camera: 0.11.0+2
  camera_android_camerax: 0.6.7+2
  firebase_storage: ^12.3.5
  cloud_firestore: ^5.4.5
  firebase_app_check: ^0.3.1+5
  wireguard_flutter: ^0.1.3
  dart_ping: ^9.0.1
  file_picker: ^8.1.4
  workmanager: ^0.5.2
  audio_session: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700