// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBow5AlICb7ajIQDBUtD6SXapF3UWyaFW8',
    appId: '1:302859713504:web:734cc2855d88bbaf478985',
    messagingSenderId: '302859713504',
    projectId: 'fg-personalia',
    authDomain: 'fg-personalia.firebaseapp.com',
    storageBucket: 'fg-personalia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Uhydn5-yaQjoGn-7NgD7lNNtynCVmfU',
    appId: '1:302859713504:android:8d75546701ad9983478985',
    messagingSenderId: '302859713504',
    projectId: 'fg-personalia',
    storageBucket: 'fg-personalia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkqMF9asIM6aEQvODxnYdS-s1-9fsK5t8',
    appId: '1:302859713504:ios:be0b0859a74642c4478985',
    messagingSenderId: '302859713504',
    projectId: 'fg-personalia',
    storageBucket: 'fg-personalia.firebasestorage.app',
    iosBundleId: 'co.id.farmagitechs.personalia',
  );
}
